package com.example.fitnesslog.exercise.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import com.example.fitnesslog.workout.data.model.WorkoutTemplate

/**
 * Represents the association between a workout template and its exercises.
 *
 * Uses a composite primary key of [`workout_template_id` and `position`].
 * This ensures that within a specific workout template, exercises at any given position are unique.
 *
 * Composite primary keys automatically indexed by Room, providing fast lookups and sorting
 * An autogenerated primary key ID is omitted since the composite key ensures the required uniqueness.
 */
@Entity(
    tableName = "workout_template_exercise",
    primaryKeys = ["workout_template_id", "position"],
    foreignKeys = [
        ForeignKey(
            entity = WorkoutTemplate::class,
            parentColumns = ["id"],
            childColumns = ["workout_template_id"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = ExerciseTemplate::class,
            parentColumns = ["id"],
            childColumns = ["exercise_template_id"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class WorkoutTemplateExercise(
    @ColumnInfo(name = "workout_template_id") val workoutTemplateId: Int,
    @ColumnInfo(name = "exercise_template_id") val exerciseTemplateId: Int,
    @ColumnInfo(name = "position") val position: Int,
    @ColumnInfo(name = "created_at") val createdAt: Long,
    @ColumnInfo(name = "updated_at") val updatedAt: Long
)
